Develop
marat-a/explore-with-me pull request #1
Opened 2022-10-10 04:13 UTC by marat-a

2022-10-12 08:24 UTC, damirovna requested changes
Ко всем контроллерам сущностей нужно добавить аннотацию @Validated после навешивания всех аннотаций.

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +                                      views BIGINT,
[Нужно исправить] Информация о просмотрах должна быть получена из сервиса статистики. В базе основного сервиса эта информация храниться не должна

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +                                     email VARCHAR(512) NOT NULL,
[Нужно исправить] Поле должно быть UNIQUE

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +                                      state VARCHAR(100) NOT NULL,
[Можно лучше]

Можно добавить дефолтное значение

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/resources/schema.sql
> +                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
[Нужно исправить]
Данная таблица связывает две сущности событие и подброку, в данном случает поле id не нужно

2022-10-12 08:24 UTC, damirovna commented on pom.xml
> +    <dependencies>
[Нужно исправить]

В родительском pom файле не должно быть блока dependencies , так как проект многомодульный, и такой блок в родительском pom’е жёстко задаст список зависимостей для всех дочерних модулей, а в нашем случае (и в большинстве случаев) это не нужно.

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/category/model/CategoryDto.java
>    private Long id;
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe полю name

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/compilation/model/CompilationDto.java
>  public class CompilationDto   {
[Нужно исправить]

Нужно добавить аннотации @notblank и @SiZe полю title

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/event/controllers/PublicEventController.java
> +                                                  @RequestParam(required = false) String sort,
[Нужно исправть]

Для поля sort нужно использовать  enum

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/event/service/EventServiceImpl.java
> +            page = PageRequest.of(from, size, Sort.by(Sort.Direction.ASC, "views"));
[Нужно исправить]

Просмотры нужно получать из сервиса статистики, это требование ТЗ

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/event/model/EventFullDto.java
>      private String annotation;
[Нужно исправить]

Нужно добавить аннотации @NotBlank и @NotNull и @SiZe к полям:

annotation
description
title


Поле eventDate должно быть в будущем

2022-10-12 08:24 UTC, damirovna commented on main-server/src/main/java/ru/practicum/mainserver/event/model/EventFullDto.java
> +    private Long participantLimit;
[Нужно исправить]

Нужно добавить аннотацию, которая задаёт этому полю неотрицательные значения

2022-10-12 10:08 UTC, marat-a commented on main-server/src/main/resources/schema.sql
> +                                      views BIGINT,
У меня информация получалась из сервера статистики при преобразовании в DTO. В базе данные не хранились, поле было задано изначально, затем забыл убрать.

2022-10-12 10:11 UTC, marat-a commented on main-server/src/main/resources/schema.sql
> +                                     email VARCHAR(512) NOT NULL,
Ограничение по уникальности вынесено чуть ниже

2022-10-12 11:43 UTC, marat-a commented on main-server/src/main/java/ru/practicum/mainserver/category/model/CategoryDto.java
>    private Long id;
В спецификации API нет ограничения на размер поля name. И для новой категории в контроллере используется NewCategoryDto, где notblank прописан

2022-10-12 12:00 UTC, marat-a commented on main-server/src/main/java/ru/practicum/mainserver/compilation/model/CompilationDto.java
>  public class CompilationDto   {
В спецификации API нет ограничения на размер поля title. И для новой категории в контроллере используется NewCompilationDto, @Notblank добавил туда

2022-10-12 19:51 UTC, marat-a commented on main-server/src/main/java/ru/practicum/mainserver/event/model/EventFullDto.java
>      private String annotation;
В контроллере используется NewEventDto, там все ограничения указаны

2022-10-12 19:53 UTC, marat-a commented on main-server/src/main/java/ru/practicum/mainserver/event/model/EventFullDto.java
> +    private Long participantLimit;
В контроллере используется NewEventDto, там все ограничения указаны

2022-10-13 15:29 UTC, damirovna requested changes
Отличная работа! Правки внесены верно, но возвращаю на доработку, чтобы вы могли поработать над тестами! Удачи!

2022-10-13 16:54 UTC, damirovna approved these changes
Всё отлично!

2022-10-13 17:14 UTC, merged